### ISSUE TITLE
Error page when designing guides

### ISSUE THREAD

**Issue by ruth-hanna** [fengzhanglab/GUIDES#10]
I wanted to alert you to a problem with the GUIDES tool. I input the gene "HPRT1" with all of the default settings, and was taken to this page:

http://guides.sanjanalab.org/#/designer/87e65e3e-4bd5-4699-917c-2df04b1f20c4

This error occurred in both Chrome and Safari, and also occurred when I tried a few other genes. Occasionally, the tool didn't reach that error page at all, but just hung on a blank screen indefinitely.

**Comment by joshim5** [comment]
Hi @ruth-hanna, I tried running GUIDES with "HPRT1" with the default settings and don't get any errors:

http://guides.sanjanalab.org/#/designer/23663850-c7ed-4124-b77a-f3590b879db0

It's possible that you ran this while GUIDES was down for maintenance. Please let us know if there's anything we can help with!
